--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=908415), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 451, 'message': 'Start to run testcase: request methods testcase with functions, TestCase ID: 00c01bce-ed61-4ec6-81d1-c1959df9dd7b', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=25576, name='MainProcess'), 'thread': (id=23256, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 23, 41, 648488, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=910410), 'exception': None, 'extra': {}, 'file': (name='parser.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\parser.py'), 'function': 'parse_string', 'level': (name='ERROR', no=40, icon='❌'), 'line': 343, 'message': "call function error:\nfunc_name: getJoinString\nargs: ['2020-12-18', 'start']\nkwargs: {}\nTypeError: getJoinString() missing 1 required positional argument: 'behindStr'", 'module': 'parser', 'name': 'httprunner.parser', 'process': (id=25576, name='MainProcess'), 'thread': (id=23256, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 23, 41, 650483, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\parser.py", line 340, in parse_string
    func_eval_value = func(*parsed_args, **parsed_kwargs)
TypeError: getJoinString() missing 1 required positional argument: 'behindStr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=920189), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 460, 'message': 'generate testcase log: D:\\workspace\\EctRegression\\logs\\00c01bce-ed61-4ec6-81d1-c1959df9dd7b.run.log', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=25576, name='MainProcess'), 'thread': (id=23256, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 23, 41, 660262, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 456, in test_start
    TestCase(config=self.__config, teststeps=self.__teststeps)
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 334, in run_testcase
    self.__parse_config(self.__config)
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 310, in __parse_config
    config.variables, self.__project_meta.functions
  File "d:\application\python37\lib\site-packages\httprunner\parser.py", line 459, in parse_variables_mapping
    var_value, parsed_variables, functions_mapping
  File "d:\application\python37\lib\site-packages\httprunner\parser.py", line 405, in parse_data
    return parse_string(raw_data, variables_mapping, functions_mapping)
  File "d:\application\python37\lib\site-packages\httprunner\parser.py", line 340, in parse_string
    func_eval_value = func(*parsed_args, **parsed_kwargs)
TypeError: getJoinString() missing 1 required positional argument: 'behindStr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
