--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=779155), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 451, 'message': 'Start to run testcase: request methods testcase with functions, TestCase ID: c89f6564-3c58-4315-b5c6-407a0eeadf34', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 36, 59, 11086, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=407864), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: login >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 639795, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=409871), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: get admin login captcha >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 641802, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=523435), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 755366, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=523435), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 755366, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=524430), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : GET\nurl      : http://admin.ectpp.opsmart.cn/api/common/captcha/image?d=1608298620642\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "Content-Type": "Hm_lvt_ab44aa1c4d9b7bdf57dc3212a2d9b101=1607992854; sidebarStatus=1; Hm_lpvt_ab44aa1c4d9b7bdf57dc3212a2d9b101=1608032943",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-620641"\n}\ncookies  : {}\nbody     : None\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 756361, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=526576), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:00 GMT",\n    "Content-Type": "image/png",\n    "Transfer-Encoding": "chunked",\n    "Connection": "keep-alive",\n    "X-Request-ID": "4f891dcc85794a3f8c7e7bcc69b55f14",\n    "X-Protected-By": "OpenRASP",\n    "Expires": "Thu, 01 Jan 1970 00:00:00 GMT",\n    "Cache-Control": "no-store, no-cache, must-revalidate, post-check=0, pre-check=0",\n    "Pragma": "no-cache",\n    "Set-Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce; Max-Age=1800; Expires=Fri, 18-Dec-2020 14:07:00 GMT; Path=/",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nencoding : None\ncontent_type : image/png\nbody     : b\'\\x89PNG\\r\\n\\x1a\\n\\x00\\x00\\x00\\rIHDR\\x00\\x00\\x00\\x96\\x00\\x00\\x00(\\x08\\x02\\x00\\x00\\x00\\x93\\xa3\\x94\\xb0\\x00\\x00\\x03WIDATx\\xda\\xed\\xda\\xbfkTA\\x10\\x07\\xf0\\xf7\\xe7\\x19\\xb5P\\x8bk%\\xcaARXi\\x13\\x14A\\x10rZi\\x13\\x10bL\\x8a4V\\x9e\\x08*\\x16\\xdah%\\x16\\x16\\x16\\x16\\x16j\\x10D\\xc1*\\x96:00\\x0c\\xb3?\\xde\\xec\\xbe\\xd9{?\\xb2\\xcb\\x97\\xf0\\xb2\\xef\\xe58\\xee\\xc3\\xec\\xafK\\xf3\\xaf\\xb6\\x91\\xb7\\xa6~\\x04\\x95\\xb0\\xb6JX[%\\xac\\x84Sk\\xfb\\xbf\\x9ea*\\xe1X\\xfd\\xbc\\xd7V\\xedh\\xf9\\x9bR\\t\\xc7G(\\xd8\\x06\\xa2\\xd8L\\xd5\\xcf\\\\\\xd1\\x0b6\\x04\\xc5~\\x08\\xe7\\x0f\\xe6<\\xc3\\\'\\x8cPuW\\xbc\\xb5\\xbd\\xe0\\xb1!\\xdc\\xd9\\xdc\\x12\\x89\\xbfJ\\xd2\\xc3\\xa5\\t\\xe7\\x9b\\xf7)k\\x97\\xaf\\x07\\xdf\\x03{\\x0cr\\xa2\\tS\\xfdB\\x84{\\x87\\x07\\x18C\\xc2K\\xe7\\xaf\\x1e?\\xd9\\xc5\\x9c,B=Lj\\xbd\\x86\\x08\\xb9\\\\GE\\xee\\xc7m\\x84b%4+A[B\\x1895\\x84\\xc2\\xafGB\\xe1\\xb7j\\xc2\\x12%\\xd8Q\\x11\\xe7?\\x88\\xf0\\x13\\x8aI~EW\\xa4\\x1d\\xfd\\x8c\\t\\xb3\\x97\\xa3\\x08\\xc6;[\\t\\x9f?<r\\xc3m\\x0c\\to\\x1c\\\\\\xc1\\\\\\xbb\\xbb\\x01?\\x85\\x1f\\xdd\\xe5\\xb7\\xc4\\x1fz\\xefj\\x0855\\xaa%t\\x85\\xf2\\xfc\\xbc\\x84\\xa7n\\xae\\x89N\\xec\\x89\\xc8\\x85\\\\\\xcf\\x9d\\xbd\\x03q\\t?|\\xff\\x08\\xe9H\\x88\\x8a\\xfct&\\x82\\xa4\\xf1\\x8b\\x13*\\x0b\\xb4\\x7fB\\x02\\x13=\\x17\\x16\\xeb\\xaf\\xdf\\xfe\\x81p!\\xcd@\\n\\x01EN\\x08x&U\\xe8z\\x94#\\xd4\\x0f\\xb0M\\xden\\xc1\\xd0\\xcf\\x1dK\\xd1\\x8fn\\x91b+!\\x91\\xf0B\\x9c\\xad\\xdf\\xe6C+\\xfd\\xaa\\x9f\\x08C\\x84z\\xda\\xa4Q4u\\x81\\x93C\\x98\\xb7\\x8a\\x89,G\\xf9\\xfaE\\x14%v\\xa2\\xe2\\x8a\\t?\\x7fz\\x041!\\xd4\\x97`\\xc6\\xea\\xc6\\x80\\xd0\\xeah\\r\\xf7\\xf5bP\\xa5\\xbb\\xa4\\x18\\x99\\x0bq"D?b\\xa3`\\x8f\\x92\\x10\\xf1\\xf0"\\x95PY\\x82\\xde\\x82\\xcbX\\x9d&\\x13v)A\\xcd\\xd1\\x1a\\r\\xa1^\\xc2\\xf8\\x8a\\xf4\\xe2lA!!a\\xa6!$\\xbf\\x90"w\\x12\\xd7\\xfa\\x12\\x8c\\x13\\xda\\x1cs{\\xb5\\xba\\xf8\\x19\\x12\\xba\\xed\\xe7\\x9b\\xaf\\x1c\\x06\\x14\\xf9r\\x94_\\x94#\\xf4fX\\x84\\xa5\\xfd\\xa0\\x93\\x13\\xf2[qB\\xe1\\x870\\xd0)6\\x15\\xca\\xb5h+a\\xeb\\xc8\\xd9\\xd1/\\xae\\xf8\\xe3\\xd5c\\x9e&\\xe9+\\x88\\xf1\\x12\\xbaK\\x9e\\xd3g\\xb6!\\x87\\xbb_(\\xd9\\x84\\x11\\xc5\\xa4s\\x99VE4K\\xa8\\xc28a\\xf7\\xaf\\t\\x05\\x12\\xf6d\\x10"\\x95\\xb7\\xbc\\\\E\\xc2s\\xab\\x90 \\x95\\x84\\xf1\\x8dG\\xdcO\\xb9\\xa3\\x10~\\xc9\\x03\\xe9*\\ty\\\'*&\\x95\\xa0\\x9e\\x90\\xf0B\\x03)(\\xc6\\t\\xb7\\xee\\xcd0\\xc7\\xef\\x96\\xa5\\t\\xb9\\xa21a\\xe6\\x19\\xb4o_\\xef\\r7\\xd3,d\\x94\\x84\\xc0\\xa3\\x99\\x0b\\xb9\\xa2\\xd8\\x1a\\x82\\x1c\\xe7!\\xc5T?\\xfd\\xb9\\x0c\\xdd\\xb2$4\\xf1\\x8b\\x88\\x92\\x9c8`K\\x9a\\x08\\xbd\\x84\\xad%H\\x84|kOB\\xe4\\xc7\\x85P\\xd1\\xa4\\x04\\xe3\\x8a\\xde\\x89\\xb0gB\\xb7?\\xef\\x95\\x0b\\x11\\x8a\\xa9\\x8e\\xfb\\t!P\\xb4*\\xc1\\x0c\\xc5\\x89\\xfc\\x07\\x9bw\\xf1\\xe9v\\xba6JB>f&\\xdd*\\xd1\\xd26\\x15\\x13#\\xd4(\\x86\\x1e\\x18\\x0e\\xe14\\xab\\xd0\\x05\\xf3\\xfa\\x89\\xcd\\x83\\xb2\\x7f\\xf9\\xf4/\\xa4\\x12\\xaeH\\x91\\xa2\\x19-E\\xbc\\x8f\\x01^\\xad\\xc2q7"\\x0c\\x15b\\xbf~\\x95P\\xeb\\x17R\\xec\\xdd\\xaf\\x12&\\x13"\\x1be\\x08o\\xb2\\x12&\\x13\\x0e\\xadU\\xc2JX\\xac\\xed\\xbf\\xff\\x06\\x19 \\xe1\\xde\\x8b\\x97\\x98\\x81|P\\xff\\x01`a\\x1eM*t\\xb4~\\x00\\x00\\x00\\x00IEND\\xaeB`\\x82\'\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 758507, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=527395), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 111.54 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 759326, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=533405), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'returnAdminCookie': '912dd86b-0978-44a8-bf9c-abb37cf520ce'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 765336, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=534403), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 766334, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=534403), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: get admin login captcha <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 766334, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=536397), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: admin login >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 0, 768328, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=772782), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 4713, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=773780), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 5711, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=774776), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/admin/internal/user/login?username=pogba.ye&password=Change_name22\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-620769",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "0"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : None\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 6707, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=774776), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:00 GMT",\n    "Content-Length": "15",\n    "Connection": "keep-alive",\n    "X-Request-ID": "d29d72de37734e7d957300de2ae43f1f",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583"\n}\ncookies  : {}\nencoding : None\ncontent_type : \nbody     : login success!\n\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 6707, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=775774), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 235.38 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 7705, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=776771), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'cnAdminUserToken': '96c8828a-2c4d-4071-91bf-e25ebc4b3583'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 8702, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=776771), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 8702, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=777769), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: admin login <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 9700, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=778768), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: admin set tenant >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 10699, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=862932), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 94863, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=862932), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 94863, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=863930), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : PUT\nurl      : http://admin.ectpp.opsmart.cn/api/admin/internal/user/update-internal-shared-user-by-tenant/a63727e57aaa2660e0539fe716acc5ab\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-621011",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "0"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : None\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 95861, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=864927), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:00 GMT",\n    "Content-Length": "0",\n    "Connection": "keep-alive",\n    "X-Request-ID": "ebd985fa661348f5b0e987dcd6203b9a",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {}\nencoding : None\ncontent_type : \nbody     : \n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 96858, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=864927), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 83.16 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 96858, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=865924), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 97855, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=866922), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: admin set tenant <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 98853, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=866922), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step_testcase', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 286, 'message': "export variables: {'cnAdminUserToken': '96c8828a-2c4d-4071-91bf-e25ebc4b3583'}", 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 98853, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=867919), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: login <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 99850, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=868916), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: admin create price template >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 100847, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=965237), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 197168, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=966233), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 198164, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=967231), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/product/sailing/pricing-draft/GENERAL\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-621101",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "1230"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : {\n    "porName": "Shanghai",\n    "porId": "738872886232873",\n    "haulageType": "CY-CY",\n    "obHaulageType": "CY",\n    "ibHaulageType": "CY",\n    "currency": "USD",\n    "tradeLaneCode": "AAW",\n    "serviceCode": "PMX",\n    "porCityId": "738872886232873",\n    "porCityName": "Shanghai",\n    "fndCityName": "Karachi",\n    "fndCityId": "738872886233842",\n    "commodityCode": "2020-12-18automation\\u8fd0\\u4ef7\\u6a21\\u677freject",\n    "effectiveStartDate": "2020-12-18T00:00:00.000Z",\n    "effectiveEndDate": "2021-01-15T23:59:59.000Z",\n    "cargoDirectionAndPricingTag": "DEFAULT + DEFAULT",\n    "cargoDirection": "DEFAULT",\n    "pricingTag": "DEFAULT",\n    "prodType": "IP",\n    "paymentTerms": "PC",\n    "channelCode": "GENERAL",\n    "cargoType": "GENERAL",\n    "routePricingCntrDraftList": [\n        {\n            "oceanFee": 0,\n            "transferFee": 0,\n            "isNew": true,\n            "cntrType": "20GP",\n            "value": "20GP",\n            "label": "20GP",\n            "cntrTypeOptions": [\n                {\n                    "label": "20GP",\n                    "value": "20GP"\n                }\n            ],\n            "price": "111"\n        },\n        {\n            "oceanFee": 0,\n            "transferFee": 0,\n            "isNew": true,\n            "cntrType": "40GP",\n            "value": "40GP",\n            "label": "40GP",\n            "cntrTypeOptions": [\n                {\n                    "label": "40GP",\n                    "value": "40GP"\n                }\n            ],\n            "price": "222"\n        },\n        {\n            "oceanFee": 0,\n            "transferFee": 0,\n            "isNew": true,\n            "cntrType": "40HQ",\n            "value": "40HQ",\n            "label": "40HQ",\n            "cntrTypeOptions": [\n                {\n                    "label": "40HQ",\n                    "value": "40HQ"\n                }\n            ],\n            "price": "333"\n        }\n    ]\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 199162, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=967231), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:00 GMT",\n    "Content-Length": "0",\n    "Connection": "keep-alive",\n    "X-Request-ID": "d0f4ecd2e95b4c579aeb9dbfa6a7bea0",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {}\nencoding : None\ncontent_type : \nbody     : \n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 199162, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=968227), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 95.32 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 200158, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=968227), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 112, 'message': 'call hook actions: teardown request', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 200158, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=4, microseconds=969225), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 121, 'message': 'call hook function: ${sleepTime(2)}', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 1, 201156, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=970218), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 202149, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=970218), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: admin create price template <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 202149, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=6, microseconds=971219), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: search last step create successful and get template id >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 203150, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=63753), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 295684, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=63753), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 295684, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=64750), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/product/sailing/pricing-draft/GENERAL/search\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-623204",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "387"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : {\n    "serviceCode": "PMX",\n    "fndCityName": "Karachi",\n    "fndCityId": "738872886233842",\n    "status": "NEW",\n    "updateBy": "pogba.ye",\n    "sortBy": "updateTime",\n    "direction": "descending",\n    "porTransferGroupId": "",\n    "prodTypes": [],\n    "paymentTerms": [],\n    "channelCode": "GENERAL",\n    "page": 1,\n    "size": 20,\n    "commodityCode": "2020-12-18automation\\u8fd0\\u4ef7\\u6a21\\u677freject",\n    "porCityId": "738872886232873"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 296681, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=66745), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:03 GMT",\n    "Content-Type": "application/json;charset=UTF-8",\n    "Transfer-Encoding": "chunked",\n    "Connection": "keep-alive",\n    "Vary": "Accept-Encoding",\n    "X-Request-ID": "916838e99fe446c4ac64dee44d09d981",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY",\n    "Content-Encoding": "gzip"\n}\ncookies  : {}\nencoding : UTF-8\ncontent_type : application/json;charset=UTF-8\nbody     : {\n    "content": [\n        {\n            "uuid": "8aaad7707674b8ae01767611681d0152",\n            "porCityId": "738872886232873",\n            "fndCityId": "738872886233842",\n            "porCityName": "Shanghai",\n            "fndCityName": "Karachi",\n            "serviceCode": "PMX",\n            "effectiveStartDate": "2020-12-18T00:00:00.000Z",\n            "effectiveEndDate": "2021-01-15T23:59:59.000Z",\n            "haulageType": "CY-CY",\n            "status": "NEW",\n            "docId": null,\n            "updateBy": "pogba.ye",\n            "updateTime": "2020-12-18T13:37:00.957Z",\n            "tradeLaneCode": "AAW",\n            "tradeGroup": "73a12d5ca3fe43d38cdb294d8d291531",\n            "tradeArea": "LATD",\n            "porFacilityCode": null,\n            "fndFacilityCode": null,\n            "porTransferGroupId": null,\n            "porTransferGroupName": null,\n            "polId": null,\n            "polName": null,\n            "podId": null,\n            "podName": null,\n            "commodityCode": "2020-12-18automation\\u8fd0\\u4ef7\\u6a21\\u677freject",\n            "polTsMode": null,\n            "podTsMode": null,\n            "currency": "USD",\n            "channelCode": "GENERAL",\n            "paymentTerms": "PC",\n            "pricingTag": "DEFAULT",\n            "cargoDirection": "DEFAULT",\n            "prodType": "IP",\n            "cargoType": "GENERAL",\n            "routePricingCntrDraftList": [\n                {\n                    "uuid": "8aaad7707674b8ae01767611681d0153",\n                    "cntrType": "20GP",\n                    "price": 111,\n                    "currency": "USD"\n                },\n                {\n                    "uuid": "8aaad7707674b8ae01767611681d0154",\n                    "cntrType": "40GP",\n                    "price": 222,\n                    "currency": "USD"\n                },\n                {\n                    "uuid": "8aaad7707674b8ae01767611681d0155",\n                    "cntrType": "40HQ",\n                    "price": 333,\n                    "currency": "USD"\n                }\n            ],\n            "resultSummaryMap": null,\n            "outBoundHaulage": "CY",\n            "inBoundHaulage": "CY",\n            "groupingKeyForBindSvvd": "PMX_738872886232873_null_738872886233842"\n        }\n    ],\n    "pageable": {\n        "sort": {\n            "sorted": true,\n            "unsorted": false,\n            "empty": false\n        },\n        "pageSize": 20,\n        "pageNumber": 0,\n        "offset": 0,\n        "paged": true,\n        "unpaged": false\n    },\n    "totalElements": 1,\n    "last": true,\n    "totalPages": 1,\n    "first": true,\n    "sort": {\n        "sorted": true,\n        "unsorted": false,\n        "empty": false\n    },\n    "numberOfElements": 1,\n    "size": 20,\n    "number": 0,\n    "empty": false\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 298676, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=66745), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 91.53 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 298676, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=67742), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'priceTemplateId': '8aaad7707674b8ae01767611681d0152'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 299673, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=68739), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 300670, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=68739), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body.totalElements equal 1(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 300670, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=69736), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: search last step create successful and get template id <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 301667, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=70734), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: price template page bind product >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 302665, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=159362), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 391293, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=160394), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 392325, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=161361), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/product/sailing/product/GENERAL/bindSvvd\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-623302",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "36"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : [\'8aaad7707674b8ae01767611681d0152\']\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 393292, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=162388), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:03 GMT",\n    "Content-Type": "application/json;charset=UTF-8",\n    "Transfer-Encoding": "chunked",\n    "Connection": "keep-alive",\n    "Vary": "Accept-Encoding",\n    "X-Request-ID": "1b6ca87e646a419c87173c6cbaffc036",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY",\n    "Content-Encoding": "gzip"\n}\ncookies  : {}\nencoding : UTF-8\ncontent_type : application/json;charset=UTF-8\nbody     : {\n    "taskId": "29d961e0-7895-4f03-a1aa-db9985918e1c",\n    "taskGroup": null,\n    "status": "IN_PROGRESS",\n    "resultSummary": null,\n    "errorMessage": null,\n    "createBy": "pogba.ye",\n    "createdAt": "2020-12-18T13:37:03.154Z",\n    "lastUpdateAt": null,\n    "elapsedTime": 0,\n    "totalReq": 1\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 394319, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=162388), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 87.63 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 394319, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=163355), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 112, 'message': 'call hook actions: teardown request', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 395286, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=7, microseconds=164353), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 121, 'message': 'call hook function: ${sleepTime(2)}', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 3, 396284, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=164991), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'taskId': '29d961e0-7895-4f03-a1aa-db9985918e1c'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 396922, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=165692), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 397623, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=166689), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body.status equal IN_PROGRESS(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 398620, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=166689), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body.totalElements not_equal 0(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 398620, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=167686), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: price template page bind product <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 399617, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=167686), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: product release page batch submit audit >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 399617, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=382536), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 614467, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=383568), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 615499, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=384535), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/product/sailing/product/GENERAL/request-review-product\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-625400",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "1447"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : {\n    "porCity": {\n        "createTime": null,\n        "createBy": null,\n        "updateTime": "2019-05-02T00:07:51Z",\n        "updateBy": "SYS",\n        "isActive": 1,\n        "id": "738872886232873",\n        "unlocode": "CNSHA",\n        "cityName": "Shanghai",\n        "cntyName": "Shanghai",\n        "stateName": "Shanghai",\n        "stateCode": "SH",\n        "ctryName": "China",\n        "ctryCode": "CN",\n        "cityFullNameEn": "Shanghai",\n        "cityFullNameCn": "\\u4e0a\\u6d77",\n        "refUuid": null,\n        "isDummy": null\n    },\n    "fndCity": {\n        "createTime": null,\n        "createBy": null,\n        "updateTime": "2019-05-02T00:09:32Z",\n        "updateBy": "SYS",\n        "isActive": 1,\n        "id": "738872886233842",\n        "unlocode": "PKKAR",\n        "cityName": "Karachi",\n        "cntyName": null,\n        "stateName": "Sindh",\n        "stateCode": null,\n        "ctryName": "Pakistan",\n        "ctryCode": "PK",\n        "cityFullNameEn": "Karachi",\n        "cityFullNameCn": "\\u5361\\u62c9\\u5947",\n        "refUuid": null,\n        "isDummy": null\n    },\n    "serviceCode": "PMX",\n    "vesselName": "",\n    "updateBy": "pogba.ye",\n    "status": "DRAFT",\n    "pageType": "RELEASE",\n    "sortedCriteria": {\n        "releaseBatchStatus": "ALL",\n        "sortItem": "tradeLaneCode",\n        "sortOrder": "descending"\n    },\n    "targetIds": [],\n    "searchProdTypes": [],\n    "searchPaymentTerms": [],\n    "tradeLaneCode": "AAW",\n    "firstServiceCode": "",\n    "voyageNo": "",\n    "direction": "",\n    "firstPolPort": {},\n    "porFacilityCode": "",\n    "polPort": {},\n    "transitPortId": "",\n    "podPort": {},\n    "lastPodPort": {},\n    "fndFacilityCode": "",\n    "channelCode": "GENERAL",\n    "commodityCode": "2020-12-18automation\\u8fd0\\u4ef7\\u6a21\\u677freject",\n    "notificationParam": {\n        "isTrusted": true\n    },\n    "sendEmail": false\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 616466, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=385539), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:05 GMT",\n    "Content-Type": "text/plain;charset=UTF-8",\n    "Content-Length": "45",\n    "Connection": "keep-alive",\n    "X-Request-ID": "01cef3a440a34265b8348d7318f86a8a",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {}\nencoding : UTF-8\ncontent_type : text/plain;charset=UTF-8\nbody     : {\n    "businessKey": "pogba.ye-20201218213705238"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 617470, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=386530), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 213.85 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 618461, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=387527), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'reviewBusinessKey': 'pogba.ye-20201218213705238'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 619458, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=387527), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 619458, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=388524), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body.businessKey contains pogba.ye(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 620455, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=388524), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: product release page batch submit audit <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 620455, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=389550), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: product review page get review task id >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 621481, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=494682), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 726613, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=495640), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 727571, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=496641), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : GET\nurl      : http://admin.ectpp.opsmart.cn/api/workflow/internal/GENERAL/task/pending\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-625621",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : None\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 728572, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=496641), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:05 GMT",\n    "Content-Type": "application/json;charset=UTF-8",\n    "Transfer-Encoding": "chunked",\n    "Connection": "keep-alive",\n    "Vary": "Accept-Encoding",\n    "X-Request-ID": "f82ceb1a86274b8b89d58eb17f475f07",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY",\n    "Content-Encoding": "gzip"\n}\ncookies  : {}\nencoding : UTF-8\ncontent_type : application/json;charset=UTF-8\nbody     : [{\'businessKey\': \'pogba.ye-20201218213705238\', \'taskId\': \'1e055f2c-4136-11eb-872c-0208820c5d4a\', \'processName\': \'SailingProductPublish\', \'params\': {\'tenantId\': \'a63727e57aaa2660e0539fe716acc5ab\', \'batchId\': \'pogba.ye-20201218213705238\'}, \'createTime\': \'2020-12-18T13:37:05.264Z\'}]\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 728572, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=497640), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 104.13 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 729571, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=498637), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 112, 'message': 'call hook actions: teardown request', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 730568, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=9, microseconds=498637), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__call_hooks', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 121, 'message': 'call hook function: ${sleepTime(2)}', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 5, 730568, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=500092), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'extract', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 176, 'message': "extract mapping: {'reviewTaskId': '1e055f2c-4136-11eb-872c-0208820c5d4a'}", 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 7, 732023, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=500993), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 7, 732924, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=500993), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert body[0].businessKey equal pogba.ye-20201218213705238(str)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 7, 732924, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=501993), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: product review page get review task id <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 7, 733924, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=501993), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: product review page audit reject >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 7, 733924, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=878645), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 110576, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=879677), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 111608, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=880671), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-627734",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "87"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : {\n    "taskId": "1e055f2c-4136-11eb-872c-0208820c5d4a",\n    "comment": "automation\\u62d2\\u7edd"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 112602, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=880671), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 200\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:07 GMT",\n    "Content-Length": "0",\n    "Connection": "keep-alive",\n    "X-Request-ID": "c5880fd9b1ed4f39a193120473d2cbca",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {}\nencoding : None\ncontent_type : \nbody     : \n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 112602, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=881671), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 219, 'message': 'status_code: 200, response_time(ms): 375.66 ms, response_length: 0 bytes', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 113602, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=882666), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 246, 'message': 'assert status_code equal 200(int)\t==> pass', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 114597, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=882666), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 304, 'message': 'run step end: product review page audit reject <<<<<<\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 114597, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=883649), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': '__run_step', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 292, 'message': 'run step begin: product review page audit reject >>>>>>', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 115580, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=952361), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 187, 'message': 'client IP: 10.222.145.201, Port: 64116', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 184292, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=953394), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 195, 'message': 'server IP: 172.22.224.71, Port: 80', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 185325, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=954389), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== request details ==================\nmethod   : POST\nurl      : http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject\nheaders  : {\n    "User-Agent": "python-requests/2.24.0",\n    "Accept-Encoding": "gzip, deflate",\n    "Accept": "*/*",\n    "Connection": "keep-alive",\n    "X-Auth-Token": "96c8828a-2c4d-4071-91bf-e25ebc4b3583",\n    "Content-Type": "application/json;charset=UTF-8",\n    "HRUN-Request-ID": "HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-628116",\n    "Cookie": "ECTIMGCAPTCHA=912dd86b-0978-44a8-bf9c-abb37cf520ce",\n    "Content-Length": "97"\n}\ncookies  : {\n    "ECTIMGCAPTCHA": "912dd86b-0978-44a8-bf9c-abb37cf520ce"\n}\nbody     : {\n    "taskId": "1e055f2c-4136-11eb-872c-0208820c5d4a",\n    "comment": "2020-12-18automation\\u62d2\\u7edd"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 186320, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=955385), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'log_print', 'level': (name='DEBUG', no=10, icon='üêû'), 'line': 40, 'message': '\n================== response details ==================\nstatus_code : 500\nheaders  : {\n    "Server": "nginx",\n    "Date": "Fri, 18 Dec 2020 13:37:07 GMT",\n    "Content-Type": "application/json;charset=UTF-8",\n    "Transfer-Encoding": "chunked",\n    "Connection": "keep-alive",\n    "X-Request-ID": "edb3517542ed4a7b9a50fd60822a8dfe",\n    "X-Protected-By": "OpenRASP",\n    "X-Content-Type-Options": "nosniff",\n    "X-XSS-Protection": "1; mode=block",\n    "Cache-Control": "no-cache, no-store, max-age=0, must-revalidate",\n    "Pragma": "no-cache",\n    "Expires": "0",\n    "X-Frame-Options": "DENY"\n}\ncookies  : {}\nencoding : UTF-8\ncontent_type : application/json;charset=UTF-8\nbody     : {\n    "timestamp": "2020-12-18T13:37:07.959+0000",\n    "status": 500,\n    "error": "Internal Server Error",\n    "message": "{\\"code\\":\\"400003\\",\\"message\\":\\"task\\u4e0d\\u5b58\\u5728\\"}",\n    "path": "/api/workflow/internal/product/task/reject"\n}\n', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 187316, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=955385), 'exception': None, 'extra': {}, 'file': (name='client.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\client.py'), 'function': 'request', 'level': (name='ERROR', no=40, icon='‚ùå'), 'line': 216, 'message': '500 Server Error:  for url: http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject', 'module': 'client', 'name': 'httprunner.client', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 187316, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\client.py", line 214, in request
    response.raise_for_status()
  File "d:\application\python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=957380), 'exception': None, 'extra': {}, 'file': (name='response.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\response.py'), 'function': 'validate', 'level': (name='ERROR', no=40, icon='‚ùå'), 'line': 263, 'message': 'assert status_code equal 200(int)\t==> fail\ncheck_item: status_code\ncheck_value: 500(int)\nassert_method: equal\nexpect_value: 200(int)', 'module': 'response', 'name': 'httprunner.response', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 189311, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\response.py", line 244, in validate
    assert_func(check_value, expect_value, message)
  File "d:\application\python37\lib\site-packages\httprunner\builtin\comparators.py", line 10, in equal
    assert check_value == expect_value, message
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=958382), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'log_req_resp_details', 'level': (name='ERROR', no=40, icon='‚ùå'), 'line': 194, 'message': '\n******************************** DETAILED REQUEST & RESPONSE ********************************\n====== request details ======\nurl: http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject\nmethod: POST\nheaders: {\'X-Auth-Token\': \'96c8828a-2c4d-4071-91bf-e25ebc4b3583\', \'Content-Type\': \'application/json;charset=UTF-8\', \'HRUN-Request-ID\': \'HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-628116\'}\nparams: {}\ndata: None\ncookies: {}\ntimeout: 120\nallow_redirects: True\nverify: False\njson: {\'taskId\': \'1e055f2c-4136-11eb-872c-0208820c5d4a\', \'comment\': \'2020-12-18automationÊãíÁªù\'}\n\n====== response details ======\nstatus_code: 500\nheaders: {\'Server\': \'nginx\', \'Date\': \'Fri, 18 Dec 2020 13:37:07 GMT\', \'Content-Type\': \'application/json;charset=UTF-8\', \'Transfer-Encoding\': \'chunked\', \'Connection\': \'keep-alive\', \'X-Request-ID\': \'edb3517542ed4a7b9a50fd60822a8dfe\', \'X-Protected-By\': \'OpenRASP\', \'X-Content-Type-Options\': \'nosniff\', \'X-XSS-Protection\': \'1; mode=block\', \'Cache-Control\': \'no-cache, no-store, max-age=0, must-revalidate\', \'Pragma\': \'no-cache\', \'Expires\': \'0\', \'X-Frame-Options\': \'DENY\'}\nbody: \'{"timestamp":"2020-12-18T13:37:07.959+0000","status":500,"error":"Internal Server Error","message":"{\\\\"code\\\\":\\\\"400003\\\\",\\\\"message\\\\":\\\\"task‰∏çÂ≠òÂú®\\\\"}","path":"/api/workflow/internal/product/task/reject"}\'\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 190313, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 209, in __run_step_request
    validators, variables_mapping, self.__project_meta.functions
  File "d:\application\python37\lib\site-packages\httprunner\response.py", line 270, in validate
    raise ValidationFailure(failures_string)
httprunner.exceptions.ValidationFailure: assert status_code equal 200(int)	==> fail
check_item: status_code
check_value: 500(int)
assert_method: equal
expect_value: 200(int)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=958382), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'log_req_resp_details', 'level': (name='ERROR', no=40, icon='‚ùå'), 'line': 194, 'message': '\n******************************** DETAILED REQUEST & RESPONSE ********************************\n====== request details ======\nurl: http://admin.ectpp.opsmart.cn/api/workflow/internal/product/task/reject\nmethod: POST\nheaders: {\'X-Auth-Token\': \'96c8828a-2c4d-4071-91bf-e25ebc4b3583\', \'Content-Type\': \'application/json;charset=UTF-8\', \'HRUN-Request-ID\': \'HRUN-c89f6564-3c58-4315-b5c6-407a0eeadf34-628116\'}\nparams: {}\ndata: None\ncookies: {}\ntimeout: 120\nallow_redirects: True\nverify: False\njson: {\'taskId\': \'1e055f2c-4136-11eb-872c-0208820c5d4a\', \'comment\': \'2020-12-18automationÊãíÁªù\'}\n\n====== response details ======\nstatus_code: 500\nheaders: {\'Server\': \'nginx\', \'Date\': \'Fri, 18 Dec 2020 13:37:07 GMT\', \'Content-Type\': \'application/json;charset=UTF-8\', \'Transfer-Encoding\': \'chunked\', \'Connection\': \'keep-alive\', \'X-Request-ID\': \'edb3517542ed4a7b9a50fd60822a8dfe\', \'X-Protected-By\': \'OpenRASP\', \'X-Content-Type-Options\': \'nosniff\', \'X-XSS-Protection\': \'1; mode=block\', \'Cache-Control\': \'no-cache, no-store, max-age=0, must-revalidate\', \'Pragma\': \'no-cache\', \'Expires\': \'0\', \'X-Frame-Options\': \'DENY\'}\nbody: \'{"timestamp":"2020-12-18T13:37:07.959+0000","status":500,"error":"Internal Server Error","message":"{\\\\"code\\\\":\\\\"400003\\\\",\\\\"message\\\\":\\\\"task‰∏çÂ≠òÂú®\\\\"}","path":"/api/workflow/internal/product/task/reject"}\'\n', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 190313, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 209, in __run_step_request
    validators, variables_mapping, self.__project_meta.functions
  File "d:\application\python37\lib\site-packages\httprunner\response.py", line 270, in validate
    raise ValidationFailure(failures_string)
httprunner.exceptions.ValidationFailure: assert status_code equal 200(int)	==> fail
check_item: status_code
check_value: 500(int)
assert_method: equal
expect_value: 200(int)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_file_sink.py", line 179, in write
    self._file.write(message)
  File "d:\application\python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 668-669: character maps to <undefined>
--- End of logging error ---
--- Logging error in Loguru Handler #0 ---
Record was: {'elapsed': datetime.timedelta(seconds=11, microseconds=960376), 'exception': None, 'extra': {}, 'file': (name='runner.py', path='d:\\application\\python37\\lib\\site-packages\\httprunner\\runner.py'), 'function': 'test_start', 'level': (name='INFO', no=20, icon='‚ÑπÔ∏è'), 'line': 460, 'message': 'generate testcase log: D:\\workspace\\EctRegression\\logs\\c89f6564-3c58-4315-b5c6-407a0eeadf34.run.log', 'module': 'runner', 'name': 'httprunner.runner', 'process': (id=3036, name='MainProcess'), 'thread': (id=20032, name='MainThread'), 'time': datetime(2020, 12, 18, 21, 37, 8, 192307, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'China Standard Time'))}
Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 456, in test_start
    TestCase(config=self.__config, teststeps=self.__teststeps)
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 357, in run_testcase
    extract_mapping = self.__run_step(step)
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 295, in __run_step
    step_data = self.__run_step_request(step)
  File "d:\application\python37\lib\site-packages\httprunner\runner.py", line 209, in __run_step_request
    validators, variables_mapping, self.__project_meta.functions
  File "d:\application\python37\lib\site-packages\httprunner\response.py", line 270, in validate
    raise ValidationFailure(failures_string)
httprunner.exceptions.ValidationFailure: assert status_code equal 200(int)	==> fail
check_item: status_code
check_value: 500(int)
assert_method: equal
expect_value: 200(int)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\application\python37\lib\site-packages\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "d:\application\python37\lib\site-packages\loguru\_simple_sinks.py", line 26, in write
    self._stream.write(message)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\yinja\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()
OSError: [WinError 6] The handle is invalid
--- End of logging error ---
